### ISSUE TITLE
Fatal error: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by michaelkdh** [amaranter/postcss-selector-prefixer#2]
Adding element selector breaks build process
Fatal error: Cannot read property 'length' of null
eg:
.container {
    color: red;
}

**Comment by michaelkdh** [comment]
https://github.com/amaranter/postcss-selector-prefixer/pull/3

**Comment by amaranter** [comment]
This is published in version 1.0.2.
Thanks 👍
